name: default_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

    - family: Montserrat
      fonts:
         - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
         - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
         - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
         - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
         - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
         - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
         - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
         - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
         - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
         - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
         - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
         - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
         - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf

    - family: Raleway
      fonts:
         - asset: assets/fonts/Raleway/Raleway-Black.ttf
         - asset: assets/fonts/Raleway/Raleway-BlackItalic.ttf
         - asset: assets/fonts/Raleway/Raleway-Bold.ttf
         - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
         - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
         - asset: assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
         - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
         - asset: assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
         - asset: assets/fonts/Raleway/Raleway-Italic.ttf
         - asset: assets/fonts/Raleway/Raleway-Light.ttf
         - asset: assets/fonts/Raleway/Raleway-LightItalic.ttf
         - asset: assets/fonts/Raleway/Raleway-Medium.ttf
         - asset: assets/fonts/Raleway/Raleway-MediumItalic.ttf
         - asset: assets/fonts/Raleway/Raleway-Regular.ttf
         - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
         - asset: assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
         - asset: assets/fonts/Raleway/Raleway-Thin.ttf
         - asset: assets/fonts/Raleway/Raleway-ThinItalic.ttf
